# generated by labs-theme from colors.toml -- do not edit
font=JetBrainsMono Nerd Font 10
background-color={{ background }}
text-color={{ bright_foreground }}
border-color={{ accent }}
progress-color=over {{ lighter_background }}
border-size=2
padding=10
width=380
default-timeout=5000
anchor=top-right
[urgency=critical]
border-color={{ red }}
default-timeout=0
[mode=do-not-disturb]
invisible=1
