/* generated by labs-theme from colors.toml -- do not edit */
@define-color background {{ background }};
@define-color lighter_background {{ lighter_background }};
@define-color foreground {{ foreground }};
@define-color bright_foreground {{ bright_foreground }};
@define-color dark_foreground {{ dark_foreground }};
@define-color muted {{ muted }};
@define-color accent {{ accent }};
@define-color red {{ red }};
@define-color orange {{ orange }};
