/* generated by labs-theme from colors.toml -- do not edit */
* { font-family: "JetBrainsMono Nerd Font"; font-size: 13px; }
window { background-color: {{ background }}; border: 2px solid {{ accent }}; }
#input { background-color: {{ lighter_background }}; color: {{ bright_foreground }}; border: none; margin: 8px; padding: 6px; }
#outer-box { padding: 4px; }
#entry { padding: 6px; color: {{ foreground }}; }
#entry:selected { background-color: {{ selection }}; }
#entry:selected #text { color: {{ accent }}; }
#text { color: {{ foreground }}; }
