-- Headless Hyprland config for a wayvnc virtual desktop (headless-vnc profile).
--
-- The machine has no physical display, so Hyprland has nothing to render to
-- until we create a virtual ("headless") output. There is no display manager;
-- hyprland-headless.service (systemd) starts Hyprland with this file, as the
-- desktop user.
--
-- This is plain, native Hyprland Lua (hl.bind, hl.dsp.exec_cmd, hl.on). It does
-- NOT use the Omarchy framework, which depends on sddm, limine and snapper.
--
-- Managed alongside: ~/.config/wayvnc/config
--                     ~/.config/waybar/{config.jsonc,style.css}
--                     ~/.config/chrome-flags.conf
--                     /etc/systemd/system/hyprland-headless.service
--                     /etc/systemd/system/wayvnc.service

hl.config({ autogenerated = false })

-- Pin the virtual output's mode/scale before it exists; Hyprland applies
-- this rule as soon as an output named HEADLESS-1 shows up.
-- Theme colours (borders) from labs-theme -- change with labs-theme-pick.
pcall(dofile, os.getenv("HOME") .. "/.local/state/labs-theme/current/hyprland.lua")

hl.monitor({
    output   = "HEADLESS-1",
    mode     = "1920x1080@60",
    position = "0x0",
    scale    = 1,
})

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

--------------------
---- AUTOSTART -----
--------------------

hl.on("hyprland.start", function()
    -- Create the virtual output once Hyprland has finished starting.
    -- Without this, `hyprctl monitors` stays empty forever and wayvnc has
    -- nothing to capture.
    hl.exec_cmd("hyprctl output create headless HEADLESS-1")

    -- Bring up a terminal immediately so there is at least one window on
    -- first connect, independent of whether any keybind (SUPER or
    -- otherwise) makes it through the VNC client.
    hl.exec_cmd("foot")

    -- Workspace bar. See the note in waybar's own config for why this is
    -- waybar and not Omarchy's quickshell-based bar.
    hl.exec_cmd("waybar")  -- shared ~/.config/waybar (Omarchy-style bar)
    hl.exec_cmd("mako")    -- notifications (+ do-not-disturb indicator)
    hl.exec_cmd("sh -c '[ -e $HOME/.local/state/labs-theme/current/background ] && exec swaybg -m fill -i $HOME/.local/state/labs-theme/current/background'")

    -- Chrome is installed (AUR google-chrome, built unprivileged) but is
    -- deliberately NOT autostarted here -- launch it with SUPER+B or the
    -- CTRL+ALT fallback below, or from the app list.
end)

--------------------
---- KEYBINDS ------
--------------------

-- SUPER may not reach wayvnc reliably from every VNC client (some
-- intercept Cmd/Super at the OS level before it's sent as an RFB key
-- event). Every binding below also has a CTRL+ALT fallback that doesn't
-- depend on Super at all, so a stuck/eaten Super key never fully blocks
-- you.
hl.bind("SUPER + RETURN", hl.dsp.exec_cmd("foot"), { description = "Open terminal" })
hl.bind("CTRL + ALT + RETURN", hl.dsp.exec_cmd("foot"), { description = "Open terminal (no-Super fallback)" })

hl.bind("SUPER + Q", hl.dsp.window.close(), { description = "Close window" })
hl.bind("CTRL + ALT + Q", hl.dsp.window.close(), { description = "Close window (no-Super fallback)" })

hl.bind("SUPER + LEFT", hl.dsp.focus({ direction = "l" }), { description = "Focus left" })
hl.bind("SUPER + RIGHT", hl.dsp.focus({ direction = "r" }), { description = "Focus right" })
hl.bind("SUPER + UP", hl.dsp.focus({ direction = "u" }), { description = "Focus up" })
hl.bind("SUPER + DOWN", hl.dsp.focus({ direction = "d" }), { description = "Focus down" })

hl.bind("SUPER + B", hl.dsp.exec_cmd("google-chrome-stable"), { description = "Open Google Chrome" })
hl.bind("CTRL + ALT + B", hl.dsp.exec_cmd("google-chrome-stable"), { description = "Open Google Chrome (no-Super fallback)" })

-- Omarchy-style launcher, menu and theme picker (labs-theme), 2026-09-25.
-- Super keys match Omarchy; CTRL+ALT fallbacks because VNC clients often eat Super.
hl.bind("SUPER + SPACE", hl.dsp.exec_cmd("wofi --show drun"), { description = "App launcher" })
hl.bind("CTRL + ALT + SPACE", hl.dsp.exec_cmd("wofi --show drun"), { description = "App launcher (no-Super fallback)" })
hl.bind("SUPER + ALT + SPACE", hl.dsp.exec_cmd("labs-menu"), { description = "Menu" })
hl.bind("CTRL + ALT + M", hl.dsp.exec_cmd("labs-menu"), { description = "Menu (no-Super fallback)" })
hl.bind("SUPER + CTRL + SHIFT + SPACE", hl.dsp.exec_cmd("labs-theme-pick"), { description = "Theme picker" })
hl.bind("CTRL + ALT + P", hl.dsp.exec_cmd("labs-theme-pick"), { description = "Theme picker (no-Super fallback)" })
